# ==============================================================================
# Generated by qmake (2.01a) (Qt 4.6.3) on: ??? ?? 27 16:39:06 2010
# This file is generated by qmake and should not be modified by the
# user.
#  Name        : Makefile_0xe27b6dbf.mk
#  Part of     : QtRemoteDroidClient
#  Description : This file is used to call necessary targets on wrapper makefile
#                during normal Symbian build process.
#  Version     : 
#
# ==============================================================================



MAKE = make

VISUAL_CFG = RELEASE
ifeq "$(CFG)" "UDEB"
VISUAL_CFG = DEBUG
endif

do_nothing :
	@rem do_nothing

MAKMAKE: create_temps pre_targetdeps store_build

LIB: create_temps pre_targetdeps store_build

BLD: create_temps pre_targetdeps store_build

ifeq "$(PLATFORM)" "WINSCW"
CLEAN: extension_clean winscw_deployment_clean deployment_clean
else
CLEAN: extension_clean deployment_clean
endif

CLEANLIB: do_nothing

RESOURCE: do_nothing

FREEZE: do_nothing

SAVESPACE: do_nothing

RELEASABLES: do_nothing

ifeq "$(PLATFORM)" "WINSCW"
FINAL: finalize winscw_deployment deployment
else
FINAL: finalize deployment
endif

pre_targetdeps : e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile
	-$(MAKE) -f "e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile" pre_targetdeps QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

create_temps : e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile
	-$(MAKE) -f "e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile" create_temps QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

extension_clean : e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile
	-$(MAKE) -f "e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile" extension_clean QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

finalize : e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile
	-$(MAKE) -f "e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile" finalize QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

winscw_deployment_clean : e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile
	-$(MAKE) -f "e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile" winscw_deployment_clean QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

winscw_deployment : e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile
	-$(MAKE) -f "e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile" winscw_deployment QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

deployment_clean : e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile
	-$(MAKE) -f "e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile" deployment_clean QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

deployment : e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile
	-$(MAKE) -f "e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile" deployment QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

store_build : e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile
	-$(MAKE) -f "e:\NokiaQtSDK\QtProject\QtRemoteDroidClient\Makefile" store_build QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)


